{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "9ae0059f_7dfafe90",
        "filename": "build-setup.sh",
        "patchSetId": 1
      },
      "lineNbr": 403,
      "author": {
        "id": 1001758
      },
      "writtenOn": "2023-06-22T23:02:45Z",
      "side": 1,
      "message": "Without this change what issue you were running into? The docker build was not able to reach the outside network?",
      "revId": "faab0b8e9b2b70c44a818947e98725cbd617cc71",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}